#JDBC Configutation for Database Connection
jdbc.driverClassName=${JDBC_DRIVER:com.mysql.jdbc.Driver}
jdbc.url=${JDBC_URL:jdbc:mysql://localhost:3306/accounts}
jdbc.username=${JDBC_USERNAME:root}
jdbc.password=${JDBC_PASSWORD:password}

#Memcached Configuration For Active and StandBy Host
#For Active Host
memcached.active.host=${MEMCACHED_ACTIVE_HOST:localhost}
memcached.active.port=${MEMCACHED_ACTIVE_PORT:11211}
#For StandBy Host
memcached.standBy.host=${MEMCACHED_STANDBY_HOST:localhost}
memcached.standBy.port=${MEMCACHED_STANDBY_PORT:11211}

#RabbitMq Configuration
rabbitmq.address=${RABBITMQ_ADDRESS:localhost}
rabbitmq.port=${RABBITMQ_PORT:15672}
rabbitmq.username=${RABBITMQ_USERNAME:guest}
rabbitmq.password=${RABBITMQ_PASSWORD:guest}

#Elasticesearch Configuration
elasticsearch.host=${ELASTICSEARCH_HOST:localhost}
elasticsearch.port=${ELASTICSEARCH_PORT:9300}
elasticsearch.cluster=${ELASTICSEARCH_CLUSTER:vprofile}
elasticsearch.node=${ELASTICSEARCH_NODE:vprofilenode}
