name: Build Workflow

on:
  push:
    paths:
      - '**'
  workflow_dispatch:


env:
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: ${{ secrets.AWS_REGION }}
 S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}


jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source code
        uses: actions/checkout@v4
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build artifacts
        run: | 
          mvn install
          mv target/vprofile-v2.war .
          rm -rf target
          mkdir target
          mv vprofile-v2.war target/
          ls -l target/

      - name: Upload WAR to S3
        run: |
          aws s3 cp target/vprofile-v2.war s3://${{ secrets.S3_BUCKET_NAME }}/artifacts/vprofile-v2.war













# name: Build Workflow
# on: workflow_dispatch
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Fetch Source coce
#        uses: actions/checkout@v4
#      - name: Build artifacts
#        run: | 
#           mvn install
#           mv target/vprofile-v2.war .
#           rm -rf target
#           mkdir target
#           mv vprofile-v2.war target/
#           ls -l target/
          
