name: Build Workflow

on:
  push:
    paths:
      - '**'
  workflow_dispatch:


env:
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 AWS_REGION: ${{ secrets.AWS_REGION }}
 S3_BUCKET_NAME: "aws-infra-03-s3-artifact-1"
 BEANSTALK_APP_NAME: "aws-infra-03-beanstalk-application"
 BEANSTALK_ENV_NAME: "aws-infra-03-beanstalk-environment-dev"


jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Source code
        uses: actions/checkout@v4
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build artifacts
        run: | 
          mvn install
          mv target/vprofile-v2.war .
          rm -rf target
          mkdir target
          mv vprofile-v2.war target/
          ls -l target/

      - name: Upload WAR to S3
        run: |
          aws s3 cp target/vprofile-v2.war s3://${{ env.S3_BUCKET_NAME }}/artifacts/vprofile-v2.war
      
      - name: Create Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.BEANSTALK_APP_NAME }} \
            --version-label build-${{ github.run_number }} \
            --source-bundle S3Bucket=${{ env.S3_BUCKET_NAME }},S3Key=artifacts/vprofile-v2.war \
            --auto-create-application

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.BEANSTALK_ENV_NAME }} \
            --version-label build-${{ github.run_number }}












# name: Build Workflow
# on: workflow_dispatch
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#      - name: Fetch Source coce
#        uses: actions/checkout@v4
#      - name: Build artifacts
#        run: | 
#           mvn install
#           mv target/vprofile-v2.war .
#           rm -rf target
#           mkdir target
#           mv vprofile-v2.war target/
#           ls -l target/
          
